import dashboardWhite from "@/public/assets/img/dashboard-white.svg";
import dashboardGrey from "@/public/assets/img/dashboard-grey.svg";
import timesheetGrey from "@/public/assets/img/timesheet_grey.svg";
import timesheetWhite from "@/public/assets/img/timesheet_white.svg";
import { typeOfDaysProps } from "./interfacetypes";

export const loginResponse1 = [
  {
    userInfo: {
      id: 36,
      empId: "ADM07",
      firstName: "Bill",
      middleName: "",
      lastName: "Thomas",
      etype: "EMPH",
      paySchedule: "Monthly",
      role: "E",
      hiringDate: "2011-02-08",
      hiringModelCode: "W2H",
      partialTS: null,
      punchIn: "N",
      businessUnit: "USA",
      projBasedTS: "X",
      countryCode: "US",
    },
    token:
      "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBRE0wNyIsImNsaWVudElkIjoiZGV2Iiwicm9sZSI6IlNBIiwicGF5c2NoZWR1bGUiOiJNb250aGx5IiwiZXR5cGUiOiJFTVBIIiwiYnVzaW5lc3NVbml0IjoiVVNBIiwicHVuY2hfaW4iOiJOIiwiUHJvakJhc2VkVFMiOiJYIiwiQ291bnRyeUNvZGUiOiJVUyIsIkhpcmluZ01vZGVsQ29kZSI6IlcySCIsImlhdCI6MTczMjU0MjIxMCwiZXhwIjoxNzMzMTQ3MDEwfQ.sRXo4CnW6y3DU1MOiQaraHyPCu_u7ZCmd9gCSgnOb9W_Nmij7RgJTxPUmNHaO4_tH0LyNHzKz-A0AsW_s4w9rQ",
  },
];

export const loginResponse = [
  {
    userInfo: {
      id: 36,
      empId: "ADM07",
      firstName: "Bill",
      middleName: "",
      lastName: "Thomas",
      etype: "EMPH",
      paySchedule: "Monthly",
      role: "SA",
      hiringDate: "2011-02-08",
      hiringModelCode: "W2H",
      partialTS: null,
      punchIn: "N",
      businessUnit: "USA",
      projBasedTS: "X",
      countryCode: "US",
    },
    token:
      "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBRE0wNyIsImNsaWVudElkIjoiZGV2Iiwicm9sZSI6IlNBIiwicGF5c2NoZWR1bGUiOiJNb250aGx5IiwiZXR5cGUiOiJFTVBIIiwiYnVzaW5lc3NVbml0IjoiVVNBIiwicHVuY2hfaW4iOiJOIiwiUHJvakJhc2VkVFMiOiJYIiwiQ291bnRyeUNvZGUiOiJVUyIsIkhpcmluZ01vZGVsQ29kZSI6IlcySCIsImlhdCI6MTczMjU0MjIxMCwiZXhwIjoxNzMzMTQ3MDEwfQ.sRXo4CnW6y3DU1MOiQaraHyPCu_u7ZCmd9gCSgnOb9W_Nmij7RgJTxPUmNHaO4_tH0LyNHzKz-A0AsW_s4w9rQ",
  },
];

export const roleManagement = [
  {
    roleid: "A",
    description: "Accounting",
  },
  {
    roleid: "E",
    description: "Employee",
  },
  {
    roleid: "HR",
    description: "Human Resource",
  },
  {
    roleid: "ICO",
    description: "Immigration Coordinator",
  },
  {
    roleid: "M",
    description: "Manager",
  },
  {
    roleid: "PH",
    description: "Pre Hire",
  },
  {
    roleid: "PM",
    description: "Management Role",
  },
  {
    roleid: "R",
    description: "Recruiter",
  },
  {
    roleid: "SA",
    description: "Super Admin",
  },
  {
    roleid: "SHR",
    description: "HR Director",
  },
  {
    roleid: "SHR",
    description: "Super HR",
  },
  {
    roleid: "SM",
    description: "Sales Manager",
  },
  {
    roleid: "TC",
    description: "OffShore AP/AR",
  },
  {
    roleid: "TC",
    description: "Time Coordinator",
  },
];
export const authenticateJsonData = {
  username: "ADM07",
  password: null,
  name: "Bill Thomas",
  role: "SA",
  emptype: "EMPH",
  floater: "",
  message: "Success",
  selectedDate: null,
  endDate: null,
  startDate: null,
  selectedEmpId: null,
  selectedEmpType: null,
  tsType: "Monthly",
  requestType: "",
  notifiNumber: 0,
  mobile: "1234567890",
  email: "jaikishan.v@employez.us",
  manager: "VC3955",
  mgrName: "",
  customTS: "",
  tsEntryByWeekly: "",
  altEmail: "",
  adminTS: "",
  requestId: 0,
  businessUnit: "USA",
  bUnitCode: null,
  hiringDate: "2011-02-08",
  empHireType: null,
  partialTS: null,
  visaType: "",
  department: "",
  hiringModelCode: "W2H",
  ptoFlag: "X",
  sickLeaveFlag: "X",
  casualLeaveFlag: "X",
  empTypeDiscriptions: null,
  showVacation: "X",
  fixedPTOFlag: "",
  loginType: "",
  status: "Active",
  medicalPlan: null,
  supplierId: null,
  vacationUnit: null,
  salary: 0.0,
  defaultPasswordFlag: "",
  accountingAccessInfo: [
    {
      businessId: "USA",
      businessName: "USA LLC",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: "X",
    },
    {
      businessId: "IND",
      businessName: "India Pvt Ltd.",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: null,
    },
    {
      businessId: "MCS",
      businessName: "Canada Enterprise",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: null,
    },
    {
      businessId: "Dubai",
      businessName: "Client - Dubai",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: null,
    },
    {
      businessId: "Mex",
      businessName: "Client - Mexico",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: null,
    },
    {
      businessId: "sing",
      businessName: "Client - Singapure",
      qbAccessFlag: "",
      arApAccessFalg: "AR",
      settingAccess: "X",
    },
  ],
  vactype: "",
  showPaternity: "",
  approverFlag: null,
  bulkUploadFlag: null,
  activeFlag: null,
  projBasedTS: "",
  showMaternity: "",
  termination_Date: null,
};

export const Codes = [
  {
    codeName: "Monthly",
    codeId: "M",
    value: "15",
    valueType: "D",
    information: null,
  },
  {
    codeName: "Semi-Monthly",
    codeId: "SM",
    value: "15",
    valueType: "D",
    information: null,
  },
  {
    codeName: "Bi-Weekly",
    codeId: "BW",
    value: "7",
    valueType: "D",
    information: "",
  },
  {
    codeName: "Weekly",
    codeId: "W",
    value: "1",
    valueType: "D",
    information: "",
  },
];

interface IRoleGroup {
  role: string;
  roleItems: ISidebarItem[];
}
interface ISidebarItem {
  name: string;
  path: string;
  icon: string;
  inactive: string;
  checked: boolean;
  childItems?: ISidebarItem[]; // Optional childItems array
}

export const menuItem: IRoleGroup[] = [
  {
    role: "",
    roleItems: [
      {
        name: "Dashboard",
        path: "/dashboard",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Basic",
    roleItems: [
      {
        name: "Timesheet",
        path: "/timesheet",
        icon: timesheetWhite,
        inactive: timesheetGrey,
        checked: true,
      },
      {
        name: "Expenses",
        path: "/expenses",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Time Off",
        path: "/timeoff",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Project status",
        path: "/projectstatus",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Employee list",
        path: "/employeelist",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Report",
        path: "/report/self",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
        childItems: [
          {
            name: "Self",
            path: "/report/self",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Approver",
            path: "/report/approver",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Payroll",
            path: "/report/payroll",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "HR",
            path: "/report/hr",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Sales",
            path: "/report/sales",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Utilization",
            path: "/report/utilization",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Financial",
            path: "/report/financial",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Public accesss doc",
            path: "/report/publicaccesssdoc",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
        ],
      },
      {
        name: "Employee document",
        path: "/Employee document",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Delegation",
    roleItems: [
      {
        name: "Timesheet",
        path: "/timesheet",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Expenses",
        path: "/expenses",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Manager",
    roleItems: [
      {
        name: "Approval System",
        path: "/approval system",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Resource allocation",
        path: "/resource allocation",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Project status approval",
        path: "/projectstatusapproval",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Disciplinary action",
        path: "/disciplinaryaction",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Human Resources",
    roleItems: [
      {
        name: "Employee Prehire",
        path: "/employeeprehire",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Employee create/Edit",
        path: "/employeecreate/Edit",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "I-9/E - verify",
        path: "/I-9/E-verify",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Employee doc resources",
        path: "/employeedocresources",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Immigration",
    roleItems: [
      {
        name: "Immigration docs",
        path: "/immigrationdocs",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Sales",
    roleItems: [
      {
        name: "Work order",
        path: "/workorder",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Job posting",
        path: "/jobposting",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Sub-Contract onboarding",
    roleItems: [
      {
        name: "Onboarding dashboard",
        path: "/onboardingdashboard",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Onboarding request",
        path: "/onboardingrequest",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Accounting",
    roleItems: [
      {
        name: "Receivable",
        path: "/receivable ",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Payable",
        path: "/payable",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Payroll",
    roleItems: [
      {
        name: "Extract payroll",
        path: "/extractpayroll ",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "India payroll",
        path: "/indiapayroll",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Admin",
    roleItems: [
      {
        name: "Settings",
        path: "/setting",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "subscription",
    roleItems: [
      {
        name: "Employee subscription",
        path: "/employeesubscription",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
];

// TimeSheet JSON Data

export const TimesheetDataByMonth = [
  [
    {
      showFlag: true,
      leaveLabel: "Eligible PTO/EL",
      hours: 160,
    },
    {
      showFlag: true,
      leaveLabel: "Earned PTO/EL",
      hours: 0,
    },
    {
      showFlag: true,
      leaveLabel: "Carry Fwd",
      hours: 39.99,
    },
    {
      showFlag: true,
      leaveLabel: "Balance PTO/EL",
      hours: 39.99,
    },
    {
      showFlag: true,
      leaveLabel: "Eligible Holiday",
      hours: 80,
    },
    {
      showFlag: false,
      leaveLabel: "Used Holidays",
      hours: 0,
    },
    {
      showFlag: false,
      leaveLabel: "Used Paid Leaves",
      hours: 0,
    },
    {
      showFlag: true,
      leaveLabel: "Balance Holiday",
      hours: 80,
    },
    {
      showFlag: true,
      leaveLabel: "Pay Out",
      hours: 0,
    },
    {
      showFlag: true,
      leaveLabel: "Balance SL",
      hours: 0,
    },
    {
      showFlag: true,
      leaveLabel: "Eligible SL",
      hours: 80,
    },
    {
      showFlag: true,
      leaveLabel: "Earned SL",
      hours: 0,
    },
    {
      showFlag: true,
      leaveLabel: "Eligible CL",
      hours: 0,
    },
    {
      showFlag: false,
      leaveLabel: "Earned CL",
      hours: 0,
    },
    {
      showFlag: true,
      leaveLabel: "Balance CL",
      hours: 0,
    },
  ],
  [
    {
      codeId: "BV",
      day: "11",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-11",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "12",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-12",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "13",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-13",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "14",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-14",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "15",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-15",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "18",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-18",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "19",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-19",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "20",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-20",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "21",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-21",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "22",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-10-22",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "25",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-25",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "26",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-26",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "27",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-27",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "28",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-28",
      leaveApprover: null,
    },
    {
      codeId: "BV",
      day: "29",
      status: 1,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-29",
      leaveApprover: null,
    },
  ],
  [
    {
      codeLabel: "PTO/EL",
      codeId: "V",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "ADDIDAS/demo2(R)",
      codeId: "C",
      projId: "ADDI3249",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: "ADDIDAS",
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "2024-03-01",
      endDate: "2025-05-31",
    },
    {
      codeLabel: "BRVMT",
      codeId: "BV",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Sick Leave",
      codeId: "S",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Training",
      codeId: "T",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "LOP",
      codeId: "L",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "ADDIDAS/demo2",
      codeId: "W",
      projId: "ADDI3249",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: "ADDIDAS",
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "2024-03-01",
      endDate: "2025-05-31",
    },
    {
      codeLabel: "Holiday",
      codeId: "H",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Casual Leave",
      codeId: "CL",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Bench",
      codeId: "B",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Comp Off",
      codeId: "A",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Maternity Leave",
      codeId: "ML",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
  ],
  [],
  [],
];

// CustomTimeSheet
export const customsheet = [
  {
    id: 1,
    date: "2024-01-10",
    projectName: "SnowED",
    hours: "Jon",
    comments: "Good",
  },
  {
    id: 2,
    date: "2024-01-11",
    projectName: "ProjectX",
    hours: "5",
    comments: "Completed task A",
  },
  {
    id: 3,
    date: "2024-01-12",
    projectName: "SnowED",
    hours: "7",
    comments: "Reviewed code",
  },
  {
    id: 4,
    date: "2024-01-13",
    projectName: "AlphaBuild",
    hours: "6",
    comments: "Team meeting",
  },
  {
    id: 5,
    date: "2024-01-14",
    projectName: "BetaTest",
    hours: "8",
    comments: "Fixed bugs",
  },
  {
    id: 6,
    date: "2024-01-15",
    projectName: "GammaRun",
    hours: "5",
    comments: "Initial setup",
  },
  {
    id: 7,
    date: "2024-01-16",
    projectName: "DeltaTech",
    hours: "6",
    comments: "Developed feature X",
  },
  {
    id: 8,
    date: "2024-01-17",
    projectName: "SnowED",
    hours: "7",
    comments: "Documentation",
  },
  {
    id: 9,
    date: "2024-01-18",
    projectName: "EpsilonData",
    hours: "8",
    comments: "Data analysis",
  },
  {
    id: 10,
    date: "2024-01-19",
    projectName: "ProjectX",
    hours: "4",
    comments: "Testing phase",
  },
];

// AssignedProjects
export const AssinedProjectlist = [
  { projectname: "Company1", projectid: "1" },
  { projectname: "Company2", projectid: "2" },
  { projectname: "Project 1", projectid: "3" },
  { projectname: "Project 1", projectid: "4" },
];

export const timeSheetDateByMonth = [
  [],
  [
    {
      codeId: "BV",
      day: "7",
      status: 0,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-07",
      leaveApprover: null,
    },
    {
      codeId: "T",
      day: "6",
      status: 0,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-06",
      leaveApprover: null,
    },
    {
      codeId: "L",
      day: "4",
      status: 0,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-04",
      leaveApprover: null,
    },
    {
      codeId: "L",
      day: "5",
      status: 0,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-05",
      leaveApprover: null,
    },
    {
      codeId: "L",
      day: "12",
      status: 0,
      value: 8,
      projId: "",
      comment: null,
      projName: null,
      codeName: null,
      calDate: "2024-03-12",
      leaveApprover: null,
    },
  ],
  [
    {
      codeLabel: "PTO/EL",
      codeId: "V",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "BRVMT",
      codeId: "BV",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Training",
      codeId: "T",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "LOP",
      codeId: "L",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Holiday",
      codeId: "H",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
    {
      codeLabel: "Bench",
      codeId: "B",
      projId: "",
      mondayValue: null,
      tuesdayValue: null,
      wednesdayValue: null,
      thursdayValue: null,
      fridayValue: null,
      saturdayValue: null,
      sundayValue: null,
      proName: null,
      weekTotal: null,
      mondayCmts: null,
      tuesdayCmts: null,
      wednesdayCmts: null,
      thursdayCmts: null,
      fridayCmts: null,
      saturdayCmts: null,
      sundayCmts: null,
      mondayDis: true,
      tuesdayDis: true,
      wednesdayDis: true,
      thursdayDis: true,
      fridayDis: true,
      saturdayDis: true,
      sundayDis: true,
      mondayHiredateDis: true,
      tuesdayHiredateDis: true,
      wednesdayHiredateDis: true,
      thursdayHiredateDis: true,
      fridayHiredateDis: true,
      saturdayHiredateDis: true,
      sundayHiredateDis: true,
      mondayPaySchdDis: true,
      tuesdayPaySchdDis: true,
      wednesdayPaySchdDis: true,
      thursdayPaySchdDis: true,
      fridayPaySchdDis: true,
      saturdayPaySchdDis: true,
      sundayPaySchdDis: true,
      startDate: "",
      endDate: "",
    },
  ],
  [],
  [],
];

export const summaryData = {
  timesheetData: [
    { calDate: "2024-11-25", codeId: "001", projId: "101", value: "8" },
    { calDate: "2024-11-26", codeId: "001", projId: "101", value: "4" },
  ],
  timesheetSummaryViewVM: [
    { codeId: "001", projId: "101", totalValue: 50, days: [] },
  ],
  saveOrSubmitDates: { startDate: "2024-11-24", endDate: "2024-11-30" },
};

export const sampleOverTimeData = [
  {
    projId: "101",
    projName: "Project A",
    day: "2024-11-01",
    value: 4,
    status: 1,
    comment: "Overtime approved",
  },
  {
    projId: "101",
    projName: "Project A",
    day: "2024-11-02",
    value: 5,
    status: 1,
    comment: "Overtime approved",
  },
  {
    projId: "102",
    projName: "Project B",
    day: "2024-11-01",
    value: 3,
    status: 2,
    comment: "Overtime pending",
  },
  {
    projId: "102",
    projName: "Project B",
    day: "2024-11-02",
    value: 2,
    status: 2,
    comment: "Overtime pending",
  },
];

export const sampleTimesheetData = [
  {
    calDate: "2024-11-01",
    codeId: "101",
    projId: "P1",
    value: "8",
  },
  {
    calDate: "2024-11-02",
    codeId: "101",
    projId: "P1",
    value: "6",
  },
  {
    calDate: "2024-11-03",
    codeId: "102",
    projId: "P2",
    value: "5",
  },
  {
    calDate: "2024-11-04",
    codeId: "102",
    projId: "P2",
    value: "7",
  },
];

export const sampleSummaryView = [
  {
    codeId: "101",
    projId: "",
    codeLabel: "BRVMT",
    totalValue: 0,
    days: [] as string[],
  },
  {
    codeId: "102",
    projId: "ADDI3249",
    codeLabel: "ADDIDAS/demo2(R)",
    totalValue: 40,
    days: [] as string[],
  },
];

export const dashboardLayoutData = [
  { id: "p1", label: "profile", checked: true },
  { id: "rs1", label: "Request status", checked: true },
  { id: "pe1", label: "Project extension", checked: true },
  { id: "vr1", label: "Vacation report", checked: true },
  { id: "oj1", label: "Open jobs", checked: true },
  { id: "iv1", label: "I-9 Verify", checked: true },
  { id: "sr1", label: "Sales report", checked: true },
  { id: "ph1", label: "Pending HR action", checked: true },
  { id: "pp1", label: "Policy/Procedure", checked: true },
  { id: "cu1", label: "contact-us", checked: true },
];

export const arrayList: any = [
  {
    name: "Gloria mehckilm",
    role: "Assistant manager",
    day: "Today",
  },
  {
    name: "David mechkam",
    role: "HR",
    day: "Tomorrow",
  },
];

export const salesReportDatas = [
  {
    name: "Total Sales",
    sales: "$48,568.20",
  },
  {
    name: "Total Income",
    sales: "$38,453.25",
  },
  {
    name: "Total Expenses",
    sales: "$2,453.45",
  },
  {
    name: "Pendiing",
    sales: "$482.85k",
  },
];

export const HiringCounts = [
  {
    label: "Prehire",
    count: 22,
  },
  {
    label: "Hiring",
    count: 22,
  },
  {
    label: "Onboarding",
    count: 108,
  },
  {
    label: "Supplier Onboarding",
    count: 22,
  },
];

export const ContactsList = [
  {
    id: "001",
    name: "Rose",
    role: "HR",
    mail: "rose@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "002",
    name: "John",
    role: "Developer",
    mail: "john@gmail.com",
    img: "/assets/img/Ellipse 14.svg",
  },
  {
    id: "003",
    name: "Emma",
    role: "Designer",
    mail: "emma@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "004",
    name: "Michael",
    role: "Project Manager",
    mail: "michael@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "005",
    name: "Sophia",
    role: "QA Engineer",
    mail: "sophia@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "006",
    name: "Liam",
    role: "DevOps Engineer",
    mail: "liam@gmail.com",
    img: "",
  },
  {
    id: "007",
    name: "Olivia",
    role: "Business Analyst",
    mail: "olivia@gmail.com",
    img: "",
  },
  {
    id: "008",
    name: "Noah",
    role: "Product Owner",
    mail: "noah@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "009",
    name: "Ava",
    role: "Scrum Master",
    mail: "ava@gmail.com",
    img: "/assets/img/Ellipse.svg",
  },
  {
    id: "010",
    name: "Elijah",
    role: "Technical Lead",
    mail: "elijah@gmail.com",
    img: "",
  },
  {
    id: "011",
    name: "Charlotte",
    role: "Software Architect",
    mail: "charlotte@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "012",
    name: "James",
    role: "Database Administrator",
    mail: "james@gmail.com",
    img: "/assets/img/Ellipse.svg",
  },
  {
    id: "013",
    name: "Amelia",
    role: "System Analyst",
    mail: "amelia@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "014",
    name: "William",
    role: "Frontend Developer",
    mail: "william@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "015",
    name: "Mia",
    role: "Backend Developer",
    mail: "mia@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "016",
    name: "Benjamin",
    role: "Cloud Engineer",
    mail: "benjamin@gmail.com",
    img: "/assets/img/Ellipse 14.svg",
  },
  {
    id: "017",
    name: "Harper",
    role: "Security Analyst",
    mail: "harper@gmail.com",
    img: "",
  },
  {
    id: "018",
    name: "Lucas",
    role: "IT Support",
    mail: "lucas@gmail.com",
    img: "/assets/img/user2.svg",
  },
  {
    id: "019",
    name: "Evelyn",
    role: "Network Engineer",
    mail: "evelyn@gmail.com",
    img: "",
  },
  {
    id: "020",
    name: "Henry",
    role: "UX Researcher",
    mail: "henry@gmail.com",
    img: "",
  },
];

export const dropdownData = [
  { id: 1, label: "INDIA" },
  { id: 2, label: "USA" },
  { id: 3, label: "KOREA" },
];

export const timeOff = [
  { id: 1, label: "Request Time Off" },
  { id: 2, label: "Time Off Status" },
];
export const selfrepots = [
  { id: 1, label: "Vacation report" },
  { id: 2, label: "Change report" },
  { id: 3, label: "Download report" },
  { id: 4, label: "Disciplinary report" },
  { id: 5, label: "Punch in/Out report" },
];
export const approverrepots = [
  { id: 1, label: "Punch in/Out report" },
  { id: 2, label: "Project time approval" },
  { id: 3, label: "Custom TS details report" },
  { id: 4, label: "Reportees" },
  { id: 5, label: "Disciplinary action" },
];

export const TimeOffRequestList = [
  { id: "1876", name: "Eligible PTO/EL", count: "20", hrs: "4" },
  { id: "1877", name: "Sick Leave", count: "15", hrs: "2" },
  { id: "1878", name: "Casual Leave", count: "12", hrs: "3" },
  { id: "1879", name: "Maternity Leave", count: "30", hrs: "8" },
  { id: "1880", name: "Paternity Leave", count: "7", hrs: "8" },
  { id: "1881", name: "Bereavement Leave", count: "5", hrs: "8" },
  { id: "1882", name: "Personal Leave", count: "10", hrs: "4" },
  { id: "1883", name: "Unpaid Leave", count: "0", hrs: "0" },
  { id: "1884", name: "Work from Home", count: "25", hrs: "8" },
  { id: "1885", name: "Medical Leave", count: "20", hrs: "6" },
  { id: "1886", name: "Half-Day Leave", count: "10", hrs: "4" },
  { id: "1887", name: "Floating Holiday", count: "2", hrs: "8" },
  { id: "1888", name: "Compensatory Off", count: "5", hrs: "8" },
  { id: "1889", name: "Study Leave", count: "14", hrs: "8" },
  { id: "1890", name: "Emergency Leave", count: "3", hrs: "8" },
];

export const Logindata = [
  { name: "Ganesh", DOB: "2024-1-08", number: "95632451566", country: "USA" },
  { name: "Suresh", DOB: "2024-10-08", number: "956324515", country: "INDIA" },
];

export const typeOfDays: typeOfDaysProps[] = [
  {
    id: 1,
    name: "Full Day",
  },
  {
    id: 2,
    name: "Partial Day",
  },
  {
    id: 3,
    name: "Multiple Days",
  },
];

export const dummyJson = [
  { name: "Rajesh", countryCode: "USD" },
  { name: "Suresh", countryCode: "INR" },
  { name: "Ganesh", countryCode: "EUR" },
  { name: "Priya", countryCode: "GBP" },
  { name: "Anjali", countryCode: "JPY" },
  { name: "Ramesh", countryCode: "AUD" },
  { name: "Vikram", countryCode: "CAD" },
  { name: "Kiran", countryCode: "SGD" },
  { name: "Deepa", countryCode: "CHF" },
  { name: "Meera", countryCode: "CNY" },
];

export const currencyCode = [
  { countryCode: "USD", currency: "$" },
  { countryCode: "INR", currency: "₹" },
  { countryCode: "EUR", currency: "€" },
  { countryCode: "GBP", currency: "£" },
  { countryCode: "JPY", currency: "¥" },
  { countryCode: "AUD", currency: "A$" },
  { countryCode: "CAD", currency: "C$" },
  { countryCode: "SGD", currency: "S$" },
  { countryCode: "CHF", currency: "CHF" },
  { countryCode: "CNY", currency: "¥" },
];

export const dateFormatCode = [
  { countryCode: "USD", dateFormat: "MM/DD/YYYY" },
  { countryCode: "INR", dateFormat: "DD/MM/YYYY" },
  { countryCode: "EUR", dateFormat: "DD.MM.YYYY" },
  { countryCode: "GBP", dateFormat: "DD/MM/YYYY" },
  { countryCode: "JPY", dateFormat: "YYYY/MM/DD" },
  { countryCode: "AUD", dateFormat: "DD/MM/YYYY" },
  { countryCode: "CAD", dateFormat: "YYYY-MM-DD" },
  { countryCode: "SGD", dateFormat: "DD/MM/YYYY" },
  { countryCode: "CHF", dateFormat: "DD.MM.YYYY" },
  { countryCode: "CNY", dateFormat: "YYYY/MM/DD" },
];

export const tableData = [
  {
    id: 1,
    datefrom: "2024-01-10",
    dateto: "2024-01-15",
    timeOfftype: "LOP",
    status: "Accepted",
    reason: "Applied to HR",
  },
  {
    id: 2,
    datefrom: "2024-01-11",
    dateto: "2024-01-16",
    timeOfftype: "Sick Leave",
    status: "Pending",
    reason: "Medical Emergency",
  },
  {
    id: 3,
    datefrom: "2024-01-12",
    dateto: "2024-01-17",
    timeOfftype: "Casual Leave",
    status: "Rejected",
    reason: "Personal Reasons",
  },
  {
    id: 4,
    datefrom: "2024-01-13",
    dateto: "2024-01-18",
    timeOfftype: "Vacation",
    status: "Accepted",
    reason: "Vacation",
  },
  {
    id: 5,
    datefrom: "2024-01-14",
    dateto: "2024-01-19",
    timeOfftype: "Sick Leave",
    status: "Pending",
    reason: "Medical Emergency",
  },
  {
    id: 6,
    datefrom: "2024-01-15",
    dateto: "2024-01-20",
    timeOfftype: "LOP",
    status: "Accepted",
    reason: "Applied to HR",
  },
  {
    id: 7,
    datefrom: "2024-01-16",
    dateto: "2024-01-21",
    timeOfftype: "Casual Leave",
    status: "Rejected",
    reason: "Personal Reasons",
  },
  {
    id: 8,
    datefrom: "2024-01-17",
    dateto: "2024-01-22",
    timeOfftype: "Vacation",
    status: "Accepted",
    reason: "Vacation",
  },
  {
    id: 9,
    datefrom: "2024-01-18",
    dateto: "2024-01-23",
    timeOfftype: "Sick Leave",
    status: "Pending",
    reason: "Medical Emergency",
  },
  {
    id: 10,
    datefrom: "2024-01-19",
    dateto: "2024-01-24",
    timeOfftype: "LOP",
    status: "Accepted",
    reason: "Applied to HR",
  },
];

export const year = [
  { id: 1, label: "2022" },
  { id: 2, label: "2023" },
  { id: 3, label: "2024" },
  { id: 3, label: "2025" },
];

export const rows = [
  {
    employeeID: "SR389",
    employeename: "Rajan",
    date_from: "2022-12-03",
    date_to: "2022-12-04",
    time_off_type: "Sick Leave",
    status: "Approved",
    reason: "Medical",
    action: "",
  },
  {
    employeeID: "SR390",
    employeename: "Anita",
    date_from: "2023-12-05",
    date_to: "2023-12-06",
    time_off_type: "Casual Leave",
    status: "Pending",
    reason: "Family Function",
    action: "",
  },
  {
    employeeID: "SR391",
    employeename: "Vikram",
    date_from: "2023-11-28",
    date_to: "2023-11-29",
    time_off_type: "Annual Leave",
    status: "Rejected",
    reason: "Not Enough Balance",
    action: "",
  },
  {
    employeeID: "SR392",
    employeename: "Divya",
    date_from: "2023-12-10",
    date_to: "2023-12-12",
    time_off_type: "Maternity Leave",
    status: "Approved",
    reason: "Pregnancy",
    action: "",
  },
  {
    employeeID: "SR393",
    employeename: "Suraj",
    date_from: "2023-12-01",
    date_to: "2023-12-02",
    time_off_type: "Paternity Leave",
    status: "Approved",
    reason: "Newborn Baby",
    action: "",
  },
  {
    employeeID: "SR394",
    employeename: "Meera",
    date_from: "2024-12-20",
    date_to: "2024-12-25",
    time_off_type: "Annual Leave",
    status: "Pending",
    reason: "Vacation",
    action: "",
  },
  {
    employeeID: "SR395",
    employeename: "Gokul",
    date_from: "2023-11-15",
    date_to: "2023-11-18",
    time_off_type: "Sick Leave",
    status: "Approved",
    reason: "Fever and Cold",
    action: "",
  },
  {
    employeeID: "SR396",
    employeename: "Priya",
    date_from: "2024-12-18",
    date_to: "2024-12-22",
    time_off_type: "Vacation Leave",
    status: "Pending",
    reason: "Travel",
    action: "",
  },
  {
    employeeID: "SR397",
    employeename: "Manoj",
    date_from: "2023-12-07",
    date_to: "2023-12-07",
    time_off_type: "Half-Day Leave",
    status: "Approved",
    reason: "Personal Work",
    action: "",
  },
  {
    employeeID: "SR398",
    employeename: "Anjali",
    date_from: "2024-12-12",
    date_to: "2024-12-12",
    time_off_type: "Compensatory Off",
    status: "Approved",
    reason: "Worked on Weekend",
    action: "",
  },
  {
    employeeID: "SR399",
    employeename: "Rahul",
    date_from: "2024-12-30",
    date_to: "2024-12-31",
    time_off_type: "Casual Leave",
    status: "Pending",
    reason: "Family Visit",
    action: "",
  },
  {
    employeeID: "SR400",
    employeename: "Kavya",
    date_from: "2024-12-22",
    date_to: "2024-12-22",
    time_off_type: "Half-Day Leave",
    status: "Approved",
    reason: "Doctor Appointment",
    action: "",
  },
  {
    employeeID: "SR401",
    employeename: "Aditya",
    date_from: "2022-12-01",
    date_to: "2022-12-03",
    time_off_type: "Sick Leave",
    status: "Approved",
    reason: "Flu and Fever",
    action: "",
  },
  {
    employeeID: "SR402",
    employeename: "Sanjana",
    date_from: "2023-12-25",
    date_to: "2023-12-27",
    time_off_type: "Casual Leave",
    status: "Rejected",
    reason: "High Workload",
    action: "",
  },
  {
    employeeID: "SR403",
    employeename: "Arjun",
    date_from: "2023-12-26",
    date_to: "2023-12-28",
    time_off_type: "Annual Leave",
    status: "Approved",
    reason: "Year-End Vacation",
    action: "",
  },
  {
    employeeID: "SR404",
    employeename: "Neha",
    date_from: "2023-12-15",
    date_to: "2023-12-15",
    time_off_type: "Compensatory Off",
    status: "Approved",
    reason: "Worked on Holiday",
    action: "",
  },
  {
    employeeID: "SR405",
    employeename: "Ramesh",
    date_from: "2023-12-04",
    date_to: "2023-12-05",
    time_off_type: "Sick Leave",
    status: "Pending",
    reason: "Medical Checkup",
    action: "",
  },
  {
    employeeID: "SR406",
    employeename: "Sridevi",
    date_from: "2023-12-08",
    date_to: "2023-12-08",
    time_off_type: "Half-Day Leave",
    status: "Approved",
    reason: "Bank Work",
    action: "",
  },
  {
    employeeID: "SR407",
    employeename: "Karthik",
    date_from: "2023-12-02",
    date_to: "2023-12-06",
    time_off_type: "Annual Leave",
    status: "Approved",
    reason: "Vacation",
    action: "",
  },
  {
    employeeID: "SR408",
    employeename: "Harini",
    date_from: "2024-12-09",
    date_to: "2024-12-11",
    time_off_type: "Sick Leave",
    status: "Approved",
    reason: "Back Pain",
    action: "",
  },
  {
    employeeID: "SR407",
    employeename: "Karthik",
    date_from: "2023-12-02",
    date_to: "2023-12-06",
    time_off_type: "Annual Leave",
    status: "Approved",
    reason: "Vacation",
    action: "",
  },
  {
    employeeID: "SR408",
    employeename: "Harini",
    date_from: "2024-12-09",
    date_to: "2024-12-11",
    time_off_type: "Sick Leave",
    status: "Approved",
    reason: "Back Pain",
    action: "",
  },
];

export const rowsForApprover = [
  {
    employeeId: "SR389",
    employeename: "Rajan",
    date: "2022-12-03",
    status: "Present",
    punchin: "12:00pm",
    punchout: "09:00pm",
    duration: "09:00",
    reason: "Medical",
  },
  {
    employeeId: "SR390",
    employeename: "Anjali",
    date: "2022-12-04",
    status: "Present",
    punchin: "09:00am",
    punchout: "06:00pm",
    duration: "09:00",
    reason: "None",
  },
  {
    employeeId: "SR391",
    employeename: "Manish",
    date: "2022-12-05",
    status: "Sick Leave",
    punchin: "-",
    punchout: "-",
    duration: "00:00",
    reason: "Sick",
  },
  {
    employeeId: "SR392",
    employeename: "Priya",
    date: "2022-12-06",
    status: "Present",
    punchin: "10:00am",
    punchout: "07:00pm",
    duration: "09:00",
    reason: "None",
  },
  {
    employeeId: "SR393",
    employeename: "Vikram",
    date: "2022-12-07",
    status: "Late",
    punchin: "11:00am",
    punchout: "08:00pm",
    duration: "09:00",
    reason: "Traffic",
  },
  {
    employeeId: "SR394",
    employeename: "Neha",
    date: "2022-12-08",
    status: "Present",
    punchin: "09:30am",
    punchout: "06:30pm",
    duration: "09:00",
    reason: "None",
  },
  {
    employeeId: "SR395",
    employeename: "Arjun",
    date: "2022-12-09",
    status: "Present",
    punchin: "09:15am",
    punchout: "06:15pm",
    duration: "09:00",
    reason: "None",
  },
  {
    employeeId: "SR396",
    employeename: "Divya",
    date: "2022-12-10",
    status: "Half Day",
    punchin: "09:00am",
    punchout: "01:00pm",
    duration: "04:00",
    reason: "Personal",
  },
  {
    employeeId: "SR397",
    employeename: "Karan",
    date: "2022-12-11",
    status: "Present",
    punchin: "08:45am",
    punchout: "05:45pm",
    duration: "09:00",
    reason: "None",
  },
  {
    employeeId: "SR398",
    employeename: "Simran",
    date: "2022-12-12",
    status: "Casual Leave",
    punchin: "-",
    punchout: "-",
    duration: "00:00",
    reason: "Vacation",
  },
  {
    employeeId: "SR399",
    employeename: "Amit",
    date: "2022-12-13",
    status: "Present",
    punchin: "09:00am",
    punchout: "06:00pm",
    duration: "09:00",
    reason: "None",
  },
  {
    employeeId: "SR400",
    employeename: "Sara",
    date: "2022-12-14",
    status: "Late",
    punchin: "10:30am",
    punchout: "07:30pm",
    duration: "09:00",
    reason: "Delayed",
  },
  {
    employeeId: "SR401",
    employeename: "Rahul",
    date: "2022-12-15",
    status: "Present",
    punchin: "09:00am",
    punchout: "06:00pm",
    duration: "09:00",
    reason: "None",
  },
  {
    employeeId: "SR402",
    employeename: "Pooja",
    date: "2022-12-16",
    status: "Present",
    punchin: "09:00am",
    punchout: "06:00pm",
    duration: "09:00",
    reason: "None",
  },
  {
    employeeId: "SR403",
    employeename: "Rohan",
    date: "2022-12-17",
    status: "Half Day",
    punchin: "09:00am",
    punchout: "01:00pm",
    duration: "04:00",
    reason: "Personal",
  },
];

export const columns = [
  { id: 1, key: "employeeID", label: "Employee ID", checked: true },
  { id: 2, key: "employeename", label: "Employee Name", checked: false },
  { id: 3, key: "date_from", label: "Date From", checked: true },
  { id: 4, key: "date_to", label: "Date To", checked: true },
  { id: 5, key: "time_off_type", label: "Time off Type", checked: false },
  { id: 6, key: "status", label: "Status", checked: true },
  { id: 7, key: "reason", label: "Reason", checked: true },
  { id: 8, key: "action", label: "Action", checked: true },
];


export const columnForApprover = [
  { id: 1, key: "employeeId", label: "Employee ID", checked: true },
  { id: 2, key: "employeename", label: "Employee Name", checked: false },
  { id: 3, key: "date", label: "Date", checked: true },
  { id: 4, key: "status", label: "Status", checked: true },
  { id: 5, key: "punchin", label: "Punch In", checked: false },
  { id: 6, key: "punchout", label: "Punch Out", checked: true },
  { id: 7, key: "duration", label: "Duration", checked: true },
  { id: 8, key: "reason", label: "Reason", checked: true },
];

export const requestTable = [
  {
    id: "rt1",
    request_type: "Personal Contact",
    submitted_date: "24/11/2024",
    approved_by: "Christopher",
    status: "Approved",
  },
  {
    id: "rt2",
    request_type: "Leave Request",
    submitted_date: "25/11/2024",
    approved_by: "Jessica",
    status: "Pending",
  },
  {
    id: "rt3",
    request_type: "Travel Reimbursement",
    submitted_date: "26/11/2024",
    approved_by: "Michael",
    status: "Rejected",
  },
  {
    id: "rt4",
    request_type: "Medical Leave",
    submitted_date: "27/11/2024",
    approved_by: "Jennifer",
    status: "Approved",
  },
  {
    id: "rt5",
    request_type: "Training Enrollment",
    submitted_date: "28/11/2024",
    approved_by: "David",
    status: "Pending",
  },
  {
    id: "rt6",
    request_type: "Work From Home",
    submitted_date: "29/11/2024",
    approved_by: "Laura",
    status: "Approved",
  },
  {
    id: "rt7",
    request_type: "Overtime Request",
    submitted_date: "30/11/2024",
    approved_by: "Robert",
    status: "Approved",
  },
  {
    id: "rt8",
    request_type: "Shift Change",
    submitted_date: "01/12/2024",
    approved_by: "Linda",
    status: "Rejected",
  },
  {
    id: "rt9",
    request_type: "Personal Contact",
    submitted_date: "02/12/2024",
    approved_by: "William",
    status: "Pending",
  },
  {
    id: "rt10",
    request_type: "Expense Report",
    submitted_date: "03/12/2024",
    approved_by: "Elizabeth",
    status: "Approved",
  },
  {
    id: "rt11",
    request_type: "Leave Request",
    submitted_date: "04/12/2024",
    approved_by: "Daniel",
    status: "Approved",
  },
  {
    id: "rt12",
    request_type: "Travel Reimbursement",
    submitted_date: "05/12/2024",
    approved_by: "Matthew",
    status: "Pending",
  },
  {
    id: "rt13",
    request_type: "Medical Leave",
    submitted_date: "06/12/2024",
    approved_by: "Anthony",
    status: "Rejected",
  },
  {
    id: "rt14",
    request_type: "Training Enrollment",
    submitted_date: "07/12/2024",
    approved_by: "Patricia",
    status: "Approved",
  },
  {
    id: "rt15",
    request_type: "Work From Home",
    submitted_date: "08/12/2024",
    approved_by: "Barbara",
    status: "Pending",
  },
  {
    id: "rt16",
    request_type: "Overtime Request",
    submitted_date: "09/12/2024",
    approved_by: "James",
    status: "Approved",
  },
  {
    id: "rt17",
    request_type: "Shift Change",
    submitted_date: "10/12/2024",
    approved_by: "Thomas",
    status: "Rejected",
  },
  {
    id: "rt18",
    request_type: "Personal Contact",
    submitted_date: "11/12/2024",
    approved_by: "Charles",
    status: "Pending",
  },
  {
    id: "rt19",
    request_type: "Expense Report",
    submitted_date: "12/12/2024",
    approved_by: "Karen",
    status: "Approved",
  },
  {
    id: "rt20",
    request_type: "Leave Request",
    submitted_date: "13/12/2024",
    approved_by: "Donald",
    status: "Approved",
  },
];