import dashboardWhite from "../assets/img/dashboard-white.svg";
import dashboardGrey from "../assets/img/dashboard-grey.svg";
import timesheetGrey from "../assets/img/timesheet_grey.svg";
import timesheetWhite from "../assets/img/timesheet_white.svg";

export const loginResponse1 =[
  {
    "userInfo": {
      "id": 36,
      "empId": "ADM07",
      "firstName": "Bill",
      "middleName": "",
      "lastName": "Thomas",
      "etype": "EMPH",
      "paySchedule": "Monthly",
      "role": "SAB",
      "hiringDate": "2011-02-08",
      "hiringModelCode": "W2H",
      "partialTS": null,
      "punchIn": "N",
      "businessUnit": "USA",
      "projBasedTS": "X",
      "countryCode": "US"
    },
    "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBRE0wNyIsImNsaWVudElkIjoiZGV2Iiwicm9sZSI6IlNBIiwicGF5c2NoZWR1bGUiOiJNb250aGx5IiwiZXR5cGUiOiJFTVBIIiwiYnVzaW5lc3NVbml0IjoiVVNBIiwicHVuY2hfaW4iOiJOIiwiUHJvakJhc2VkVFMiOiJYIiwiQ291bnRyeUNvZGUiOiJVUyIsIkhpcmluZ01vZGVsQ29kZSI6IlcySCIsImlhdCI6MTczMjU0MjIxMCwiZXhwIjoxNzMzMTQ3MDEwfQ.sRXo4CnW6y3DU1MOiQaraHyPCu_u7ZCmd9gCSgnOb9W_Nmij7RgJTxPUmNHaO4_tH0LyNHzKz-A0AsW_s4w9rQ"
  }
]

export const loginResponse =[
  {
    "userInfo": {
      "id": 36,
      "empId": "ADM07",
      "firstName": "Bill",
      "middleName": "",
      "lastName": "Thomas",
      "etype": "EMPH",
      "paySchedule": "Monthly",
      "role": "SA",
      "hiringDate": "2011-02-08",
      "hiringModelCode": "W2H",
      "partialTS": null,
      "punchIn": "N",
      "businessUnit": "USA",
      "projBasedTS": "X",
      "countryCode": "US"
    },
    "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBRE0wNyIsImNsaWVudElkIjoiZGV2Iiwicm9sZSI6IlNBIiwicGF5c2NoZWR1bGUiOiJNb250aGx5IiwiZXR5cGUiOiJFTVBIIiwiYnVzaW5lc3NVbml0IjoiVVNBIiwicHVuY2hfaW4iOiJOIiwiUHJvakJhc2VkVFMiOiJYIiwiQ291bnRyeUNvZGUiOiJVUyIsIkhpcmluZ01vZGVsQ29kZSI6IlcySCIsImlhdCI6MTczMjU0MjIxMCwiZXhwIjoxNzMzMTQ3MDEwfQ.sRXo4CnW6y3DU1MOiQaraHyPCu_u7ZCmd9gCSgnOb9W_Nmij7RgJTxPUmNHaO4_tH0LyNHzKz-A0AsW_s4w9rQ"
  }
]
export const authenticateJsonData = {
  username: "ADM07",
  password: null,
  name: "Bill Thomas",
  role: "SA",
  emptype: "EMPH",
  floater: "",
  message: "Success",
  selectedDate: null,
  endDate: null,
  startDate: null,
  selectedEmpId: null,
  selectedEmpType: null,
  tsType: "Monthly",
  requestType: "",
  notifiNumber: 0,
  mobile: "1234567890",
  email: "jaikishan.v@employez.us",
  manager: "VC3955",
  mgrName: "",
  customTS: "",
  tsEntryByWeekly: "",
  altEmail: "",
  adminTS: "",
  requestId: 0,
  businessUnit: "USA",
  bUnitCode: null,
  hiringDate: "2011-02-08",
  empHireType: null,
  partialTS: null,
  visaType: "",
  department: "",
  hiringModelCode: "W2H",
  ptoFlag: "X",
  sickLeaveFlag: "X",
  casualLeaveFlag: "X",
  empTypeDiscriptions: null,
  showVacation: "X",
  fixedPTOFlag: "",
  loginType: "",
  status: "Active",
  medicalPlan: null,
  supplierId: null,
  vacationUnit: null,
  salary: 0.0,
  defaultPasswordFlag: "",
  accountingAccessInfo: [
    {
      businessId: "USA",
      businessName: "USA LLC",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: "X",
    },
    {
      businessId: "IND",
      businessName: "India Pvt Ltd.",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: null,
    },
    {
      businessId: "MCS",
      businessName: "Canada Enterprise",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: null,
    },
    {
      businessId: "Dubai",
      businessName: "Client - Dubai",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: null,
    },
    {
      businessId: "Mex",
      businessName: "Client - Mexico",
      qbAccessFlag: "X",
      arApAccessFalg: "AC",
      settingAccess: null,
    },
    {
      businessId: "sing",
      businessName: "Client - Singapure",
      qbAccessFlag: "",
      arApAccessFalg: "AR",
      settingAccess: "X",
    },
  ],
  vactype: "",
  showPaternity: "",
  approverFlag: null,
  bulkUploadFlag: null,
  activeFlag: null,
  projBasedTS: "",
  showMaternity: "",
  termination_Date: null,
};

export const Codes = [
  {
    codeName: "Monthly",
    codeId: "M",
    value: "15",
    valueType: "D",
    information: null,
  },
  {
    codeName: "Semi-Monthly",
    codeId: "SM",
    value: "15",
    valueType: "D",
    information: null,
  },
  {
    codeName: "Bi-Weekly",
    codeId: "BW",
    value: "7",
    valueType: "D",
    information: "",
  },
  {
    codeName: "Weekly",
    codeId: "W",
    value: "1",
    valueType: "D",
    information: "",
  },
];

interface IRoleGroup {
  role: string;
  roleItems: ISidebarItem[];
  
}
interface ISidebarItem {
  name: string;
  path: string;
  icon: string;
  inactive: string;
  checked: boolean;
  childItems?: ISidebarItem[]; // Optional childItems array
}

export const menuItem: IRoleGroup[] = [
  {
    role: "",
    roleItems: [
      {
        name: "Dashboard",
        path: "/dashboard",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Basic",
    roleItems: [
      {
        name: "Timesheet",
        path: "/timesheet",
        icon: timesheetWhite,
        inactive: timesheetGrey,
        checked: true,
      },
      {
        name: "Expenses",
        path: "/expenses",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Time Off",
        path: "/Timeoff",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Project status",
        path: "/Projectstatus",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Employee list",
        path: "/Employee list",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Report",
        path: "/report",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
        childItems: [
          {
            name: "Self",
            path: "/report/self",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Approver",
            path: "/report/approver",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Payroll",
            path: "/report/payroll",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "HR",
            path: "/report/hr",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Sales",
            path: "/report/sales",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Utilization",
            path: "/report/utilization",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Financial",
            path: "/report/financial",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
          {
            name: "Public accesss doc",
            path: "/report/publicaccesssdoc",
            icon: dashboardGrey,
            inactive: dashboardGrey,
            checked: true,
          },
        ],
      },
      {
        name: "Employee document",
        path: "/Employee document",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Delegation",
    roleItems: [
      {
        name: "Timesheet",
        path: "/timesheet",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Expenses",
        path: "/expenses",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Manager",
    roleItems: [
      {
        name: "Approval System",
        path: "/approval system",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Resource allocation",
        path: "/resource allocation",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Project status approval",
        path: "/project status approval",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Disciplinary action",
        path: "/disciplinary action",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Human Resources",
    roleItems: [
      {
        name: "Employee Prehire",
        path: "/employee prehire",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Employee create/Edit",
        path: "/employee create/Edit",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "I-9/E - verify",
        path: "/I-9/E-verify",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Employee doc resources",
        path: "/employee doc resources",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Immigration",
    roleItems: [
      {
        name: "Immigration docs",
        path: "/immigration docs",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Sales",
    roleItems: [
      {
        name: "Work order",
        path: "/work order",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Job posting",
        path: "/job posting",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Sub-Contract onboarding",
    roleItems: [
      {
        name: "Onboarding dashboard",
        path: "/onboarding dashboard",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Onboarding request",
        path: "/onboarding request",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Accounting",
    roleItems: [
      {
        name: "Receivable",
        path: "/receivable ",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "Payable",
        path: "/payable",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Payroll",
    roleItems: [
      {
        name: "Extract payroll",
        path: "/extract payroll ",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
      {
        name: "India payroll",
        path: "/india payroll",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "Admin",
    roleItems: [
      {
        name: "Settings",
        path: "/setting",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },
  {
    role: "subscription",
    roleItems: [
      {
        name: "Employee subscription",
        path: "/employee subscription",
        icon: dashboardWhite,
        inactive: dashboardGrey,
        checked: true,
      },
    ],
  },

];

// TimeSheet JSON Data

export const TimesheetDataByMonth = [
  [
      {
          "showFlag": true,
          "leaveLabel": "Eligible PTO/EL",
          "hours": 160
      },
      {
          "showFlag": true,
          "leaveLabel": "Earned PTO/EL",
          "hours": 0
      },
      {
          "showFlag": true,
          "leaveLabel": "Carry Fwd",
          "hours": 39.99
      },
      {
          "showFlag": true,
          "leaveLabel": "Balance PTO/EL",
          "hours": 39.99
      },
      {
          "showFlag": true,
          "leaveLabel": "Eligible Holiday",
          "hours": 80
      },
      {
          "showFlag": false,
          "leaveLabel": "Used Holidays",
          "hours": 0
      },
      {
          "showFlag": false,
          "leaveLabel": "Used Paid Leaves",
          "hours": 0
      },
      {
          "showFlag": true,
          "leaveLabel": "Balance Holiday",
          "hours": 80
      },
      {
          "showFlag": true,
          "leaveLabel": "Pay Out",
          "hours": 0
      },
      {
          "showFlag": true,
          "leaveLabel": "Balance SL",
          "hours": 0
      },
      {
          "showFlag": true,
          "leaveLabel": "Eligible SL",
          "hours": 80
      },
      {
          "showFlag": true,
          "leaveLabel": "Earned SL",
          "hours": 0
      },
      {
          "showFlag": true,
          "leaveLabel": "Eligible CL",
          "hours": 0
      },
      {
          "showFlag": false,
          "leaveLabel": "Earned CL",
          "hours": 0
      },
      {
          "showFlag": true,
          "leaveLabel": "Balance CL",
          "hours": 0
      }
  ],
  [
      {
          "codeId": "BV",
          "day": "11",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-11",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "12",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-12",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "13",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-13",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "14",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-14",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "15",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-15",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "18",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-18",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "19",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-19",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "20",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-20",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "21",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-21",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "22",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-10-22",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "25",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-25",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "26",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-26",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "27",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-27",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "28",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-28",
          "leaveApprover": null
      },
      {
          "codeId": "BV",
          "day": "29",
          "status": 1,
          "value": 8,
          "projId": "",
          "comment": null,
          "projName": null,
          "codeName": null,
          "calDate": "2024-03-29",
          "leaveApprover": null
      }
  ],
  [
      {
          "codeLabel": "PTO/EL",
          "codeId": "V",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "ADDIDAS/demo2(R)",
          "codeId": "C",
          "projId": "ADDI3249",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": "ADDIDAS",
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "2024-03-01",
          "endDate": "2025-05-31"
      },
      {
          "codeLabel": "BRVMT",
          "codeId": "BV",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "Sick Leave",
          "codeId": "S",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "Training",
          "codeId": "T",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "LOP",
          "codeId": "L",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "ADDIDAS/demo2",
          "codeId": "W",
          "projId": "ADDI3249",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": "ADDIDAS",
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "2024-03-01",
          "endDate": "2025-05-31"
      },
      {
          "codeLabel": "Holiday",
          "codeId": "H",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "Casual Leave",
          "codeId": "CL",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "Bench",
          "codeId": "B",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "Comp Off",
          "codeId": "A",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      },
      {
          "codeLabel": "Maternity Leave",
          "codeId": "ML",
          "projId": "",
          "mondayValue": null,
          "tuesdayValue": null,
          "wednesdayValue": null,
          "thursdayValue": null,
          "fridayValue": null,
          "saturdayValue": null,
          "sundayValue": null,
          "proName": null,
          "weekTotal": null,
          "mondayCmts": null,
          "tuesdayCmts": null,
          "wednesdayCmts": null,
          "thursdayCmts": null,
          "fridayCmts": null,
          "saturdayCmts": null,
          "sundayCmts": null,
          "mondayDis": true,
          "tuesdayDis": true,
          "wednesdayDis": true,
          "thursdayDis": true,
          "fridayDis": true,
          "saturdayDis": true,
          "sundayDis": true,
          "mondayHiredateDis": true,
          "tuesdayHiredateDis": true,
          "wednesdayHiredateDis": true,
          "thursdayHiredateDis": true,
          "fridayHiredateDis": true,
          "saturdayHiredateDis": true,
          "sundayHiredateDis": true,
          "mondayPaySchdDis": true,
          "tuesdayPaySchdDis": true,
          "wednesdayPaySchdDis": true,
          "thursdayPaySchdDis": true,
          "fridayPaySchdDis": true,
          "saturdayPaySchdDis": true,
          "sundayPaySchdDis": true,
          "startDate": "",
          "endDate": ""
      }
  ],
  [],
  []
]

// CustomTimeSheet
export const customsheet = [
  {
    id: 1,
    date: "2024-01-10",
    projectName: "SnowED",
    hours: "Jon",
    comments: "Good",
  },
  {
    id: 2,
    date: "2024-01-11",
    projectName: "ProjectX",
    hours: "5",
    comments: "Completed task A",
  },
  {
    id: 3,
    date: "2024-01-12",
    projectName: "SnowED",
    hours: "7",
    comments: "Reviewed code",
  },
  {
    id: 4,
    date: "2024-01-13",
    projectName: "AlphaBuild",
    hours: "6",
    comments: "Team meeting",
  },
  {
    id: 5,
    date: "2024-01-14",
    projectName: "BetaTest",
    hours: "8",
    comments: "Fixed bugs",
  },
  {
    id: 6,
    date: "2024-01-15",
    projectName: "GammaRun",
    hours: "5",
    comments: "Initial setup",
  },
  {
    id: 7,
    date: "2024-01-16",
    projectName: "DeltaTech",
    hours: "6",
    comments: "Developed feature X",
  },
  {
    id: 8,
    date: "2024-01-17",
    projectName: "SnowED",
    hours: "7",
    comments: "Documentation",
  },
  {
    id: 9,
    date: "2024-01-18",
    projectName: "EpsilonData",
    hours: "8",
    comments: "Data analysis",
  },
  {
    id: 10,
    date: "2024-01-19",
    projectName: "ProjectX",
    hours: "4",
    comments: "Testing phase",
  },
];

// AssignedProjects
export const AssinedProjectlist = [
  { projectname: "Company1", projectid: "1" },
  { projectname: "Company2", projectid: "2" },
  { projectname: "Project 1", projectid: "3" },
  { projectname: "Project 1", projectid: "4" },
];

export const timeSheetDateByMonth=[
  [],
  [
    {
      "codeId": "BV",
      "day": "7",
      "status": 0,
      "value": 8,
      "projId": "",
      "comment": null,
      "projName": null,
      "codeName": null,
      "calDate": "2024-03-07",
      "leaveApprover": null
    },
    {
      "codeId": "T",
      "day": "6",
      "status": 0,
      "value": 8,
      "projId": "",
      "comment": null,
      "projName": null,
      "codeName": null,
      "calDate": "2024-03-06",
      "leaveApprover": null
    },
    {
      "codeId": "L",
      "day": "4",
      "status": 0,
      "value": 8,
      "projId": "",
      "comment": null,
      "projName": null,
      "codeName": null,
      "calDate": "2024-03-04",
      "leaveApprover": null
    },
    {
      "codeId": "L",
      "day": "5",
      "status": 0,
      "value": 8,
      "projId": "",
      "comment": null,
      "projName": null,
      "codeName": null,
      "calDate": "2024-03-05",
      "leaveApprover": null
    },
    {
      "codeId": "L",
      "day": "12",
      "status": 0,
      "value": 8,
      "projId": "",
      "comment": null,
      "projName": null,
      "codeName": null,
      "calDate": "2024-03-12",
      "leaveApprover": null
    }
  ],
  [
    {
      "codeLabel": "PTO/EL",
      "codeId": "V",
      "projId": "",
      "mondayValue": null,
      "tuesdayValue": null,
      "wednesdayValue": null,
      "thursdayValue": null,
      "fridayValue": null,
      "saturdayValue": null,
      "sundayValue": null,
      "proName": null,
      "weekTotal": null,
      "mondayCmts": null,
      "tuesdayCmts": null,
      "wednesdayCmts": null,
      "thursdayCmts": null,
      "fridayCmts": null,
      "saturdayCmts": null,
      "sundayCmts": null,
      "mondayDis": true,
      "tuesdayDis": true,
      "wednesdayDis": true,
      "thursdayDis": true,
      "fridayDis": true,
      "saturdayDis": true,
      "sundayDis": true,
      "mondayHiredateDis": true,
      "tuesdayHiredateDis": true,
      "wednesdayHiredateDis": true,
      "thursdayHiredateDis": true,
      "fridayHiredateDis": true,
      "saturdayHiredateDis": true,
      "sundayHiredateDis": true,
      "mondayPaySchdDis": true,
      "tuesdayPaySchdDis": true,
      "wednesdayPaySchdDis": true,
      "thursdayPaySchdDis": true,
      "fridayPaySchdDis": true,
      "saturdayPaySchdDis": true,
      "sundayPaySchdDis": true,
      "startDate": "",
      "endDate": ""
    },
    {
      "codeLabel": "BRVMT",
      "codeId": "BV",
      "projId": "",
      "mondayValue": null,
      "tuesdayValue": null,
      "wednesdayValue": null,
      "thursdayValue": null,
      "fridayValue": null,
      "saturdayValue": null,
      "sundayValue": null,
      "proName": null,
      "weekTotal": null,
      "mondayCmts": null,
      "tuesdayCmts": null,
      "wednesdayCmts": null,
      "thursdayCmts": null,
      "fridayCmts": null,
      "saturdayCmts": null,
      "sundayCmts": null,
      "mondayDis": true,
      "tuesdayDis": true,
      "wednesdayDis": true,
      "thursdayDis": true,
      "fridayDis": true,
      "saturdayDis": true,
      "sundayDis": true,
      "mondayHiredateDis": true,
      "tuesdayHiredateDis": true,
      "wednesdayHiredateDis": true,
      "thursdayHiredateDis": true,
      "fridayHiredateDis": true,
      "saturdayHiredateDis": true,
      "sundayHiredateDis": true,
      "mondayPaySchdDis": true,
      "tuesdayPaySchdDis": true,
      "wednesdayPaySchdDis": true,
      "thursdayPaySchdDis": true,
      "fridayPaySchdDis": true,
      "saturdayPaySchdDis": true,
      "sundayPaySchdDis": true,
      "startDate": "",
      "endDate": ""
    },
    {
      "codeLabel": "Training",
      "codeId": "T",
      "projId": "",
      "mondayValue": null,
      "tuesdayValue": null,
      "wednesdayValue": null,
      "thursdayValue": null,
      "fridayValue": null,
      "saturdayValue": null,
      "sundayValue": null,
      "proName": null,
      "weekTotal": null,
      "mondayCmts": null,
      "tuesdayCmts": null,
      "wednesdayCmts": null,
      "thursdayCmts": null,
      "fridayCmts": null,
      "saturdayCmts": null,
      "sundayCmts": null,
      "mondayDis": true,
      "tuesdayDis": true,
      "wednesdayDis": true,
      "thursdayDis": true,
      "fridayDis": true,
      "saturdayDis": true,
      "sundayDis": true,
      "mondayHiredateDis": true,
      "tuesdayHiredateDis": true,
      "wednesdayHiredateDis": true,
      "thursdayHiredateDis": true,
      "fridayHiredateDis": true,
      "saturdayHiredateDis": true,
      "sundayHiredateDis": true,
      "mondayPaySchdDis": true,
      "tuesdayPaySchdDis": true,
      "wednesdayPaySchdDis": true,
      "thursdayPaySchdDis": true,
      "fridayPaySchdDis": true,
      "saturdayPaySchdDis": true,
      "sundayPaySchdDis": true,
      "startDate": "",
      "endDate": ""
    },
    {
      "codeLabel": "LOP",
      "codeId": "L",
      "projId": "",
      "mondayValue": null,
      "tuesdayValue": null,
      "wednesdayValue": null,
      "thursdayValue": null,
      "fridayValue": null,
      "saturdayValue": null,
      "sundayValue": null,
      "proName": null,
      "weekTotal": null,
      "mondayCmts": null,
      "tuesdayCmts": null,
      "wednesdayCmts": null,
      "thursdayCmts": null,
      "fridayCmts": null,
      "saturdayCmts": null,
      "sundayCmts": null,
      "mondayDis": true,
      "tuesdayDis": true,
      "wednesdayDis": true,
      "thursdayDis": true,
      "fridayDis": true,
      "saturdayDis": true,
      "sundayDis": true,
      "mondayHiredateDis": true,
      "tuesdayHiredateDis": true,
      "wednesdayHiredateDis": true,
      "thursdayHiredateDis": true,
      "fridayHiredateDis": true,
      "saturdayHiredateDis": true,
      "sundayHiredateDis": true,
      "mondayPaySchdDis": true,
      "tuesdayPaySchdDis": true,
      "wednesdayPaySchdDis": true,
      "thursdayPaySchdDis": true,
      "fridayPaySchdDis": true,
      "saturdayPaySchdDis": true,
      "sundayPaySchdDis": true,
      "startDate": "",
      "endDate": ""
    },
    {
      "codeLabel": "Holiday",
      "codeId": "H",
      "projId": "",
      "mondayValue": null,
      "tuesdayValue": null,
      "wednesdayValue": null,
      "thursdayValue": null,
      "fridayValue": null,
      "saturdayValue": null,
      "sundayValue": null,
      "proName": null,
      "weekTotal": null,
      "mondayCmts": null,
      "tuesdayCmts": null,
      "wednesdayCmts": null,
      "thursdayCmts": null,
      "fridayCmts": null,
      "saturdayCmts": null,
      "sundayCmts": null,
      "mondayDis": true,
      "tuesdayDis": true,
      "wednesdayDis": true,
      "thursdayDis": true,
      "fridayDis": true,
      "saturdayDis": true,
      "sundayDis": true,
      "mondayHiredateDis": true,
      "tuesdayHiredateDis": true,
      "wednesdayHiredateDis": true,
      "thursdayHiredateDis": true,
      "fridayHiredateDis": true,
      "saturdayHiredateDis": true,
      "sundayHiredateDis": true,
      "mondayPaySchdDis": true,
      "tuesdayPaySchdDis": true,
      "wednesdayPaySchdDis": true,
      "thursdayPaySchdDis": true,
      "fridayPaySchdDis": true,
      "saturdayPaySchdDis": true,
      "sundayPaySchdDis": true,
      "startDate": "",
      "endDate": ""
    },
    {
      "codeLabel": "Bench",
      "codeId": "B",
      "projId": "",
      "mondayValue": null,
      "tuesdayValue": null,
      "wednesdayValue": null,
      "thursdayValue": null,
      "fridayValue": null,
      "saturdayValue": null,
      "sundayValue": null,
      "proName": null,
      "weekTotal": null,
      "mondayCmts": null,
      "tuesdayCmts": null,
      "wednesdayCmts": null,
      "thursdayCmts": null,
      "fridayCmts": null,
      "saturdayCmts": null,
      "sundayCmts": null,
      "mondayDis": true,
      "tuesdayDis": true,
      "wednesdayDis": true,
      "thursdayDis": true,
      "fridayDis": true,
      "saturdayDis": true,
      "sundayDis": true,
      "mondayHiredateDis": true,
      "tuesdayHiredateDis": true,
      "wednesdayHiredateDis": true,
      "thursdayHiredateDis": true,
      "fridayHiredateDis": true,
      "saturdayHiredateDis": true,
      "sundayHiredateDis": true,
      "mondayPaySchdDis": true,
      "tuesdayPaySchdDis": true,
      "wednesdayPaySchdDis": true,
      "thursdayPaySchdDis": true,
      "fridayPaySchdDis": true,
      "saturdayPaySchdDis": true,
      "sundayPaySchdDis": true,
      "startDate": "",
      "endDate": ""
    }
  ],
  [],
  []
]

export const summaryData = {
  "timesheetData": [
    { "calDate": "2024-11-25", "codeId": "001", "projId": "101", "value": "8" },
    { "calDate": "2024-11-26", "codeId": "001", "projId": "101", "value": "4" }
  ],
  "timesheetSummaryViewVM": [
    { "codeId": "001", "projId": "101", "totalValue": 50, "days": [] }
  ],
  "saveOrSubmitDates": { "startDate": "2024-11-24", "endDate": "2024-11-30" }
}

export const sampleOverTimeData = [
  {
    projId: "101",
    projName: "Project A",
    day: "2024-11-01",
    value: 4,
    status: 1,
    comment: "Overtime approved",
  },
  {
    projId: "101",
    projName: "Project A",
    day: "2024-11-02",
    value: 5,
    status: 1,
    comment: "Overtime approved",
  },
  {
    projId: "102",
    projName: "Project B",
    day: "2024-11-01",
    value: 3,
    status: 2,
    comment: "Overtime pending",
  },
  {
    projId: "102",
    projName: "Project B",
    day: "2024-11-02",
    value: 2,
    status: 2,
    comment: "Overtime pending",
  },
];

export const sampleTimesheetData = [
  {
    calDate: "2024-11-01",
    codeId: "101",
    projId: "P1",
    value: "8",
  },
  {
    calDate: "2024-11-02",
    codeId: "101",
    projId: "P1",
    value: "6",
  },
  {
    calDate: "2024-11-03",
    codeId: "102",
    projId: "P2",
    value: "5",
  },
  {
    calDate: "2024-11-04",
    codeId: "102",
    projId: "P2",
    value: "7",
  },
];

export const sampleSummaryView = [
  {
    codeId: "101",
    projId: "",
    codeLabel: "BRVMT",
    totalValue: 0,
    days: [] as string[],
  },
  {
    codeId: "102",
    projId: "ADDI3249",
    codeLabel: "ADDIDAS/demo2(R)",
    totalValue: 40,
    days: [] as string[],
  },
];

export const dashboardLayoutData = [
  { id: "p1", label: "profile", checked: true },
  { id: "rs1", label: "Request status", checked: true },
  { id: "pe1", label: "Project extension", checked: true },
  { id: "vr1", label: "Vacation report", checked: true },
  { id: "oj1", label: "Open jobs", checked: true },
  { id: "iv1", label: "I-9 Verify", checked: true },
  { id: "sr1", label: "Sales report", checked: true },
  { id: "ph1", label: "Pending HR action", checked: true },
  { id: "pp1", label: "Policy/Procedure", checked: true },
  { id: "cu1", label: "contact-us", checked: true },
];

export const arrayList: any = [
  {
    name: "Gloria mehckilm",
    role: "Assistant manager",
    day: "Today",
  },
  {
    name: "David mechkam",
    role: "HR",
    day: "Tomorrow",
  },
];

export const salesReportDatas = [
  {
    name: "Total Sales",
    sales: "$48,568.20",
  },
  {
    name: "Total Income",
    sales: "$38,453.25",
  },
  {
    name: "Total Expenses",
    sales: "$2,453.45",
  },
  {
    name: "Pendiing",
    sales: "$482.85k",
  },
];

export const HiringCounts = [
  {
    label: "Prehire",
    count: 22,
  },
  {
    label: "Hiring",
    count: 22,
  },
  {
    label: "Onboarding",
    count: 108,
  },
  {
    label: "Supplier Onboarding",
    count: 22,
  },
];
